# Site settings
title: SPIKE Research Group
email: spencer@caltech.edu
description: Webpage of the SPIKE Research Group at Imperial College London
baseurl: ""
url: "https://spike.doc.ic.ac.uk"

# Google analytics ID: Remove or use your own!
google_global_site_tag: G-QNXYS25PE9
google_tag_manager: GTM-W9F5425

# Footer info
about: >
    Structured and Probabilistic Intelligent Knowledge Engineering Group<br/>
    Department of Computing<br/>
    Imperial College London

information: >
    <a href="/contact"><i class="fa fa-envelope fa-1x"></i> Contact us</a> <br/>
    <a href="/vacancies"><i class="fa fa-users fa-1x"></i> Explore openings</a> <br/>
    <a href="/accessibility"><i class="fa fa-universal-access fa-1x"></i> Accessibility</a>

# old information
# <a href="/aboutwebsite.html"><i class="fa fa-github fa-1x"></i> Use my site as a template!</a> <br/>

# Pages shown in navbar
nav_pages:
  # - name: news
  - name: people
    subpages:
      - team
      - collaborators
      - alumni
  - name: research
    subpages:
      - publications
      - projects
      - software
  - name: outreach
  - name: contact

include:
  - .htaccess
  - _pages
  - _projects

collections:
  projects:
    output: true

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: 
  - 'jekyll/scholar'
  - jekyll-seo-tag
  - jekyll-sitemap

scholar:
  style: /publications/custom-apa.csl
  locale: en

  source: /publications/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year,author
  order: descending,ascending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  # bibliography_list_attributes:
    # reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
