# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# when using the default proxy server port
local_backend: true # For local modifcations of cms

media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
  - name: 'bibliography'
    label: 'bibliography'
    folder: 'publications/'
    extension: '.bib'
    format: 'frontmatter'
    fields:
     - { name: body }
    # files: ['ref.bib' ]
  - name: 'news'
    label: 'News'
    folder: '_posts/news/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Conform with jekyll post format. {{slug}} comes from title field
    editor:
      preview: false
    fields:

      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string', 
            hint: 'A short, snappy summary of the news item. Appears on [truncated] frontpage, and in news list'}
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Long Post (optional)', name: 'body', widget: 'markdown', required: false, 
            hint: 'If left blank then no separate post page will be linked to by the item.' }
      - { label: "Tags", name: "tags", widget: "list", default: ["news"] }
      - { label: "Featured Image (optional)", name: "thumbnail", widget: "image", required: false,
            hint: 'An image to accompany the news item. A small version is shown in list, and large item at top of post (if long-form)'}
       # Hidden from CMS users 
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'permalink', name: 'permalink', widget: 'hidden', default: '/news/:year/:month/:title/'}
  - name: 'projects'
    label: 'Projects'
    folder: '_projects'
    create: true
    slug: '{{slug}}' # {{slug}} comes from title field
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: string }
      - { label: 'Summary', name: 'summary', widget: string, 
            hint: 'A short summary of the project. Appears on project list page'}
      - { label: 'Date', name: 'date', widget: 'datetime', hint: 'Date for associated post' }
      - { label: 'Long Post (optional)', name: 'body', widget: markdown, required: false, 
            hint: 'If left blank then no separate post page will be linked to by the item.' }
      # - { label: "Tags", name: "tags", widget: "list", default: ["news"] }
      - { label: "Featured Image (optional)", name: "thumbnail", widget: image, required: false,
            hint: 'An image to accompany the project item. A small version is shown in list, and large item at top of post (if long-form)'}
       # Hidden from CMS users 
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'permalink', name: 'permalink', widget: 'hidden', default: '/projects/:title'}
      
  - name: "research"
    label: "Research Focus List"
    folder: "_data"
    format: "yaml"
    create: false
    filter: {field: "file_identifier", value: "This is the research interests file!"}
    slug: 'research_interests.yml'
    fields:
      - name: file_identifier
      - name: research_focuses
        label: "Research Focuses"
        widget: list
        fields:
          - {label: "Focus", name: focus, widget: hidden, default: "{{fields.title}}"}
          - {label: "Focus Title", name: title, widget: string, default: "Solving AGI!"}
          - {label: "Focus Description", name: description, widget: string}
          - {label: "Focus Image", name: image, widget: image, required: false}
