name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
      
      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
          cache: 'pip' # caching pip dependencies
          working-directory: ./.github/workflows/twitter-action

      - name: Pip setup
        run: pip install -r requirements.txt
        working-directory: ./.github/workflows/twitter-action

      - name: Run python script
        run: python hello.py
        working-directory: ./.github/workflows/twitter-action
