name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Get changed files in publications
        id: changed-files-pub
        uses: tj-actions/changed-files@v34
        with:
          files: |
            publications/**

      - name: Get diff lines
        id: diff
        if: steps.changed-files-pub.outputs.any_changed == 'true'
        run: |
          echo "List all the files that have changed: ${{ steps.changed-files-pub.outputs.all_changed_files }}"
          git show ${{ github.sha }}:publications/test.txt >> changes.txt
          echo "CHANGES=changes.txt" >> $GITHUB_OUTPUT

      - name: Cat the diff
        run: cat ${{ steps.diff.outputs.CHANGES }}

      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
          cache: 'pip' # caching pip dependencies

      - name: Pip setup
        run: pip install -r requirements.txt
        working-directory: ./.github/workflows/twitter-action

      - name: Run python script
        run: python hello.py
        working-directory: ./.github/workflows/twitter-action
